[package]
name = "necklace-matching"
version = "0.1.0"
authors = ["Simon <simonwoodburyforget@gmail.com>"]
edition = "2018"
license = "MPL"

[dependencies]
criterion = "0.3"
rand = "0.7"
dashmap = "3.7"
rayon = "*"

[[bench]]
name = "main"
harness = false