[tasks.wasm-clean]
script = [ "rm ./pkg/wasm_experiment.* -f" ]
dependencies = [ "clean" ]

[tasks.wasm-pack]
command = "wasm-pack"
args = ["build", "--target=web"]

[tasks.wasm-run]
description = "Build wasm and open a Firefox tab."
script = [ "firefox 0.0.0.0:8000" ]
dependencies = [ "wasm-pack" ]