[package]
name = "bare-metal-wasm"
version = "0.1.0"
authors = ["Simon <simonwoodburyforget@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

# [profile.release]
# lto = true
# opt-level = 's'

[dependencies]
